### PR TITLE
Longest Substring Without Repeating Characters #5

### PR DESCRIPTION
**Pull request by heyyviv**
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me
- [x] One Change in one Pull Request
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.
- [ ] I have added README.md with my script

### CODE REVIEW

**Comment by heyyviv** [comment]
should i add a read.md

**Comment by heyyviv** [comment]
is something is wrong with my code?

**Comment by rexdivakar** [comment]
Hey @heyyviv  can u pls add a README.md file also update ur fork since we have made multiples changes, so update ur fork add ur changes and raise a PR again !!

**Comment by BALaka-18** [comment]
@heyyviv add a screenshot of your code passing on Leetcode

**Pull request closed without merging**
