### PR TITLE
Valid Parentheses Problem

### PR DESCRIPTION
**Pull request by nirajmalpani**
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me
- [x] One Change in one Pull Request
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.
- [x] I have added README.md with my script

### CODE REVIEW

**Comment by BALaka-18** [comment]
@nirajmalpani please add a screenshot to show that the code passed successfully on Leetcode.

**Comment by nirajmalpani** [comment]
Screenshot (124)

**Comment by nirajmalpani** [comment]
do i have to add this on the folder@BALaka-18

**Comment by rexdivakar** [comment]
@nirajmalpani  please add them into a folder and update ur fork and re-raise the PR

**Comment by nirajmalpani** [comment]
I have added the screenshot please review it.

**Review by BALaka-18 — APPROVED** [review]
Ready to merge

**Pull request merged**
